Project contrans {
  database_type: 'PostgreSQL'
  Note: '''
    # Congress Transparency Dashboard Project
    Data collected from Congress.gov API, OpenSecrets.org
    **markdown content here**
  '''
}
Table members as M {
    #paste sandbox output of variables# 
    bioguideid varchar [pk]
    id int [pk, increment]
    full_name varchar
    created_at timestamp
    country_code int
    note: "members data combines congress API bio info with OpenSecrets ID and Voteview Ideology "
}
Table terms as T {
  chamber varchar
  startyear int [pk]
  bioguideid carchar [pk]
  endyear float
  
  note: "terms extracted from Congress API bio data"
}
Table votes as V {
  #pull once sql is connected
}

Ref: M.bioguideid < T.bioguideid 
Ref: M.icpsr < V.icpsr
